# GitHub CI build pipeline
name: Cookiecutter PyPackage CI build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', 'pypy3.10']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          if  [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; else pip install .; fi
      - name: Run Tests
        run: |
          pytest tests/
      - name: Run package creation
        run: |
          python -m pip install --user --upgrade build
          python -m build
      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: cookie-cutter-${{ matrix.python-version }}
          path: src/dist
